name: chestmodal
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - aiohappyeyeballs=2.4.4
  - aiohttp=3.11.10
  - aiosignal=1.2.0
  - annotated-types=0.6.0
  - anyio=4.7.0
  - arrow-cpp=19.0.0
  - async-timeout=5.0.1
  - attrs=24.3.0
  - aws-c-auth=0.6.19
  - aws-c-cal=0.5.20
  - aws-c-common=0.8.5
  - aws-c-compression=0.2.16
  - aws-c-event-stream=0.2.15
  - aws-c-http=0.6.25
  - aws-c-io=0.13.10
  - aws-c-mqtt=0.7.13
  - aws-c-s3=0.1.51
  - aws-c-sdkutils=0.1.6
  - aws-checksums=0.1.13
  - aws-crt-cpp=0.18.16
  - aws-sdk-cpp=1.11.212
  - blas=1.0
  - boost-cpp=1.82.0
  - bottleneck=1.4.2
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates
  - certifi
  - charset-normalizer=3.3.2
  - click=8.1.8
  - colorama=0.4.6
  - contourpy=1.2.1
  - cycler=0.11.0
  - datasets=3.3.2
  - dill=0.3.8
  - exceptiongroup=1.2.0
  - fastapi=0.112.2
  - fonttools=4.55.3
  - freeglut=3.4.0
  - freetype=2.13.3
  - frozenlist=1.5.0
  - gflags=2.2.2
  - glog=0.5.0
  - h11=0.14.0
  - huggingface_hub=0.29.2
  - icu=73.1
  - idna=3.7
  - importlib_resources=6.4.0
  - intel-openmp=2023.1.0
  - joblib=1.4.2
  - jpeg=9e
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil
  - libboost=1.82.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcurl=8.12.1
  - libdeflate=1.22
  - libevent=2.1.12
  - libgrpc
  - libpng=1.6.39
  - libpq=17.4
  - libprotobuf
  - libre2-11
  - libssh2=1.11.1
  - libthrift=0.15.0
  - libtiff=4.7.0
  - libwebp-base=1.3.2
  - lz4-c=1.9.4
  - matplotlib=3.9.2
  - matplotlib-base=3.9.2
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - multidict=6.1.0
  - multiprocess=0.70.15
  - numexpr=2.10.1
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openjpeg=2.5.2
  - openssl=3.0.16
  - orc=2.1.1
  - packaging=24.2
  - pandas=2.2.3
  - pip
  - propcache=0.3.1
  - protobuf
  - pyarrow=19.0.0
  - pybind11-abi=5
  - pydantic=2.10.3
  - pydantic-core=2.27.1
  - pyparsing=3.2.0
  - pyqt=6.7.1
  - pyqt6-sip=13.9.1
  - pysocks=1.7.1
  - python=3.9
  - python-dateutil=2.9.0
  - python-tzdata=2023.3
  - python-xxhash=3.5.0
  - pytz=2024.1
  - pyyaml=6.0.2
  - qtbase=6.7.3
  - qtdeclarative=6.7.3
  - qtsvg=6.7.3
  - qttools=6.7.3
  - qtwebchannel=6.7.3
  - qtwebsockets=6.7.3
  - re2
  - regex=2024.11.6
  - requests=2.32.3
  - safetensors=0.5.3
  - scikit-learn=1.5.0
  - scipy=1.13.1
  - setuptools
  - sip=6.10.0
  - six=1.17.0
  - snappy=1.2.1
  - sniffio=1.3.0
  - sqlite=3.45.3
  - starlette=0.38.2
  - tbb=2021.8.0
  - threadpoolctl=3.5.0
  - tokenizers=0.21.0
  - tomli=2.0.1
  - tornado=6.4.2
  - tqdm=4.67.1
  - transformers=4.49.0
  - typing-extensions=4.12.2
  - tzdata
  - unicodedata2=15.1.0
  - urllib3=2.3.0
  - utf8proc=2.6.1
  - uvicorn=0.32.1
  - wheel
  - xxhash=0.8.0
  - xz=5.6.4
  - yaml=0.2.5
  - yarl=1.18.0
  - zipp=3.21.0
  - zlib=1.2.13
  - zstd=1.5.6
  - pytorch=2.5.0
  - torchaudio=2.5.0
  - torchvision=0.20.0
  - pytorch-cuda=12.4
  - pip:
      - filelock==3.13.1
      - fsspec==2024.6.1
      - jinja2==3.1.4
      - markupsafe==2.1.5
      - mpmath==1.3.0
      - networkx==3.2.1
      - pillow==11.0.0
      - pydicom==2.4.4
      - sympy==1.13.1